### ISSUE TITLE
Post install scripts

### ISSUE THREAD

**Issue by oucsaw** [autopkg/chilcote-recipes#4]
Hi,

We're looking at using autopkg and munki to enable people to install Docker on their systems.

I've had a look at your recipes, which look great, but I'm a little confused. The `Docker.munki.recipe `has parent `Docker.download.recipe` and no `postinstall` script, so when you install the package you get prompted for local admin credentials at first run. 

There seems to be a post install script, which gets built into the `.pkg` file, but you've chosen not to use this with munki.

Can you enlighten me as to why you've gone down this route (without the postinstall script) ? 

We'd like to push out the Docker app with the postinstall as our uses don't have local admin rights (and also a postuninstall script ... which I've yet to write, but my plan would be to share this)

Many thanks,
aaron

**Comment by timsutton** [comment]
It might make sense to have the postinstall script in the pkg and just have Munki use the pkg recipe as a parent. (But perhaps still generate an app installs item)

I've asked Docker for Mac to consider making a cli tool for these tasks so that everyone deploying it doesn't need to keep up with it: https://github.com/docker/for-mac/issues/717.

**Comment by chilcote** [comment]
> Can you enlighten me as to why you've gone down this route (without the postinstall script) ?

The simple reason is just my own stupidity, and that I don't use munki so didn't think about it.  Luckily, stupidity is fixable with pull requests.
